# Generated by rust2rpm 28 and modified
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate yesser-todo-cli

Name:           yesser-todo-cli
Version:        1.4.0
Release:        %autorelease
Summary:        To-do CLI written in Rust

License:        AGPL-3.0
URL:            https://crates.io/crates/yesser-todo-cli
Source:         %{crates_source}
Source:         %{name}-%{version}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  openssl-devel

Requires:       openssl

%global _description %{expand:
A to-do CLI written in Rust.}

%description %{_description}

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/todo

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build -- -p yesser-todo-cli
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
install -D -p -m 0755 target/release/todo %{buildroot}%{_bindir}/todo

%if %{with check}
%check
%cargo_test -- -- --skip test_handle_show_server
%endif

%changelog
%autochangelog
