# Generated by rust2rpm 28 and modified
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate yesser-todo-server

Name:           yesser-todo-server
Version:        2.0.0
Release:        %autorelease
Summary:        Server for yesser-todo-cli written in Rust

License:        AGPL-3.0
URL:            https://crates.io/crates/yesser-todo-server
Source:         %{crates_source}
Source:         %{crate}-%{version}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A server for yesser-todo-cli written in Rust.}

%description %{_description}

%files
# %license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/yesser-todo-server

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --test-threads=1
%endif

%changelog
%autochangelog
